name: Deploy API Docs

on:
  push:
    branches:
     - main
     - workflow_apidoc

jobs:

  api:
    name: Deploy API Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11
          auto-activate-base: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install ".[doc]"

      - name: Build API documentation
        shell: bash -l {0}
        run: |
          sphinx-apidoc -Mfeo docs/source src/argosim
          sphinx-build docs/source docs/build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
